-- Table structure for table `pets`
CREATE TABLE IF NOT EXISTS public.pets
(
    pet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    pet_name character varying NOT NULL,
    level integer NOT NULL DEFAULT 1,
    hunger integer NOT NULL DEFAULT 50,
    happiness integer NOT NULL DEFAULT 50,
    last_fed timestamp without time zone,
    last_played timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT pets_pkey PRIMARY KEY (pet_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
